General docs for first milestone
Anglepi/My-Many-Reads pull request #42
Opened 2022-09-19 19:13 UTC by Anglepi

Increases the docs with:

- Entries of each user story implemented in the current milestone
- Technical decisions made so far, affecting development environment and development process

Closes #36, closes #15

#37 is not done yet and will be the last thing to finish this milestone, but will be included as a separate PR

2022-09-21 13:31 UTC, Anglepi commented
Just noticed I've missed the dataclass stuff to add in the docs, I'll add it and in the way add the requirements of next MVP

2022-09-22 10:16 UTC, JJ requested changes
Conviene que inviertas cómo justificas las elecciones: primero los criterios y alternativas, finalmente la solución.

2022-09-22 10:16 UTC, JJ commented on docs/tex/biblio.bib
> +@misc{languagespeed,
Este tipo de referencias es mejor que las pongas simplemente como enlace.

2022-09-22 10:16 UTC, JJ commented on docs/tex/secciones/04_analisis.tex
> +\subsubsection{Requisitos funcionales}
Lo de requisitos funcionales es muy waterfall y poco ágil.  Trata de encuadrarlo bien dentro del desarrollo ágil, no te vayas a pillar los dedos.

2022-09-22 10:16 UTC, JJ commented on docs/tex/secciones/05_implementacion.tex
> +En primer lugar se muestra el listado de las historias de usuario generadas junto con sus correspondientes tareas, que dan forma a las unidades de trabajo refinadas. Tras esto, se encuentran todos lo
Explica qué son las historias de usuario y cómo se enmarcan en el desarrollo ágil. El tribunal no tiene por qué estar familiarizado con ellas.

2022-09-22 10:16 UTC, JJ commented on docs/tex/secciones/05_implementacion.tex
> +    \item \href{https://github.com/Anglepi/My-Many-Reads/issues/7}{\textbf{HU-1}} Criterios de evaluación del jurado \\
Este suele ser nuestra HU "secreta". No creo que haga falta que la pongas.

2022-09-22 10:16 UTC, JJ commented on docs/tex/secciones/05_implementacion.tex
> +\textbf{Elección final:} \href{https://www.gnu.org/software/make/}{\textit{make}}.
No partas de la elección final, di como has llegado hasta ella. Un TFG es un conjunto de decisiones que tienes que justificar.

2022-09-22 10:16 UTC, JJ commented on docs/tex/secciones/05_implementacion.tex
> +\textbf{Alternativa principal:} \href{https://www.sublimetext.com/}{\textit{Sublime Text}}.
Uf, a estas alturas... Más PyCharm o emacs.

2022-09-22 10:16 UTC, JJ commented on docs/tex/secciones/05_implementacion.tex
> +\textbf{Elección final:} \href{https://python-poetry.org/}{\textit{Poetry}}
Previa a esta decisión está usar pyproject.toml, que viene aconsejado por un PEP 5xx que no me acuerdo cuál es. Una vez que elijas eso (una buena práctica), tienes poca elección, o este o hash

2022-09-22 10:16 UTC, JJ commented on docs/tex/secciones/05_implementacion.tex
> +\textbf{Almacenamiento de datos inmutables:} \href{https://docs.python.org/3/library/dataclasses.html}{\textit{Dataclasses}}
Estás mezclando herramientas con elecciones sobre el propio código. No es lo mismo, esto son simplemente elecciones que se adaptan al dominio.

2022-09-22 11:22 UTC, Anglepi commented on docs/tex/secciones/05_implementacion.tex
> +\textbf{Alternativa principal:} \href{https://www.sublimetext.com/}{\textit{Sublime Text}}.
Creo que en algún momento hice mención al hecho de que quería usar un único editor para todo lo que pudiera tener que ver con el proyecto, por lo que veía buena opción usar un editor genérico más que un IDE

2022-09-22 11:24 UTC, Anglepi commented on docs/tex/biblio.bib
> +@misc{languagespeed,
No lo vi mal ponerlo ahí en este caso, además de que en mi TFG fueron muy pesados con que pusiera mucha bibliografía... al final se me va a quedar en dos enlaces

2022-09-22 11:26 UTC, Anglepi commented on docs/tex/secciones/04_analisis.tex
> +\subsubsection{Requisitos funcionales}
Si no recuerdo mal esto ya lo hablamos anteriormente, voy a usar estos requisitos como "punto de partida" para crear las HU

2022-09-22 11:26 UTC, Anglepi commented on docs/tex/secciones/05_implementacion.tex
> +En primer lugar se muestra el listado de las historias de usuario generadas junto con sus correspondientes tareas, que dan forma a las unidades de trabajo refinadas. Tras esto, se encuentran todos lo
En serio? Estamos en 2022, no conozco a nadie que no trabaje con historias de usuario...

2022-09-22 11:27 UTC, Anglepi commented on docs/tex/secciones/05_implementacion.tex
> +    \item \href{https://github.com/Anglepi/My-Many-Reads/issues/7}{\textbf{HU-1}} Criterios de evaluación del jurado \\
Mmmm sí, debería quitarla la verdad, en su momento dudé si ponerla o no

2022-09-22 11:30 UTC, Anglepi commented on docs/tex/secciones/05_implementacion.tex
> +\textbf{Elección final:} \href{https://python-poetry.org/}{\textit{Poetry}}
Lo único que encontré para el pyproject.toml fue Poetry, por lo que las alternativas eran no seguir buenas prácticas...

2022-09-22 12:03 UTC, Anglepi commented on docs/tex/secciones/05_implementacion.tex
> +\textbf{Almacenamiento de datos inmutables:} \href{https://docs.python.org/3/library/dataclasses.html}{\textit{Dataclasses}}
Mi intención en esta sección es poner todas las importaciones notables que haga durante el proyecto y si crece mucho ya dividirlas de alguna manera.

Por otra parte, no veo tan clara la diferencia que mencionas, algo no estoy entendiendo

2022-09-22 12:18 UTC, Anglepi commented
Added some review actions for now, but I still need to clear some doubts about [this conversation](https://github.com/Anglepi/My-Many-Reads/pull/42#discussion_r977468755)

2022-09-24 08:30 UTC, JJ commented on docs/tex/secciones/05_implementacion.tex
> +\textbf{Alternativa principal:} \href{https://www.sublimetext.com/}{\textit{Sublime Text}}.
Ya, pero Sublime...

2022-09-24 08:30 UTC, JJ commented on docs/tex/secciones/05_implementacion.tex
> +\textbf{Elección final:} \href{https://python-poetry.org/}{\textit{Poetry}}
Pero es que esa es la decisión que tienes que poner, siguiendo las mejores prácticas que propusieron ese pyproject.toml.

2022-09-24 08:31 UTC, JJ commented on docs/tex/secciones/05_implementacion.tex
> +\textbf{Almacenamiento de datos inmutables:} \href{https://docs.python.org/3/library/dataclasses.html}{\textit{Dataclasses}}
Una cosa son las herramientas que eliges y otras las decisiones de diseño sobre cómo organizar el código. usar dataclasses es de esta última.

2022-09-24 09:33 UTC, Anglepi commented on docs/tex/secciones/05_implementacion.tex
> +\textbf{Elección final:} \href{https://python-poetry.org/}{\textit{Poetry}}
Está puesto en la justificación, que como poetry sigue el estándar es la elección que se ha tomado.

Decidir sobre el estándar y decidir sobre el gestor de dependencias acaba siendo lo mismo según como lo he justificado, solo cambia el título de la sección

2022-09-24 09:35 UTC, Anglepi commented on docs/tex/secciones/05_implementacion.tex
> +\textbf{Alternativa principal:} \href{https://www.sublimetext.com/}{\textit{Sublime Text}}.
Lo he puesto porque de la gente que se que trabaja con editor y no IDE lo hacen con sublime o vscode, personalmente no lo veo mal, y nunca escuché de emacs por ejemplo hasta que lo mencionaste en este comentario

2022-09-24 09:41 UTC, Anglepi commented on docs/tex/secciones/05_implementacion.tex
> +\textbf{Almacenamiento de datos inmutables:} \href{https://docs.python.org/3/library/dataclasses.html}{\textit{Dataclasses}}
Entiendo, pues puedo quitarla de momento y comentarlo al final cuándo sepa que el código no va a cambiar, que será cuando explique un poco las diferentes clases y etc. que he diseñado

2022-09-28 10:40 UTC, JJ approved these changes
Me parece válida, pero mejorable en la línea que he ido comentando.

2022-09-28 10:40 UTC, JJ commented on docs/tex/secciones/05_implementacion.tex
> +En primer lugar se muestra el listado de las historias de usuario generadas junto con sus correspondientes tareas, que dan forma a las unidades de trabajo refinadas. Tras esto, se encuentran todos lo
Te recuerdo quien forma el tribunal. Algunos no saben ni lo que es GitHub.

2022-09-28 10:40 UTC, JJ commented on docs/tex/secciones/05_implementacion.tex
> +Las historias de usuario se usan para definir funcionalidades que ciertos tipos de usuarios desean en determinadas situaciones. Cada una de estas historias de usuario representa un avance en la funci
Más bien para expresar el beneficio que esperan los usuarios. Las funcionalidades las tienes que deducir tú

2022-09-28 10:40 UTC, JJ commented on docs/tex/secciones/05_implementacion.tex
> +    con el fin de saber si me pueden interesar según sus características.
Este sería el beneficio. Lo que hay arriba debería ser un simple issue. En general, las historias de usuario sólo están en el dominio del problema. Pero a estas alturas da un poco igual.

2022-09-28 10:40 UTC, JJ commented on docs/tex/secciones/05_implementacion.tex
> +\textbf{Elección final:} \href{https://www.gnu.org/software/make/}{\textit{make}}.
:arrow_up:

2022-09-28 10:40 UTC, JJ commented on docs/tex/secciones/05_implementacion.tex
> +Es un editor muy popular, que además recibe actualizaciones de manera frecuente con notables mejoras.
No lo veo como alternativa principal, pero supongo que todo esto lo reescribirás más o menos.

2022-09-28 10:40 UTC, JJ commented on docs/tex/secciones/05_implementacion.tex
> +Finalmente se ha ido consensuando una buena práctica para estas gestiones, por lo que ésta ha de ser tenida en cuenta.
Indica que se trata de un PEP.

2022-09-28 10:40 UTC, JJ commented on docs/tex/secciones/05_implementacion.tex
> +\textbf{Alternativa:} \href{https://pipenv-es.readthedocs.io/es/latest/}{\textit{Pipenv}}
Y no has dicho cuál has elegido. Siempre lo sueles poner antes, ¿no?

2022-09-28 10:40 UTC, JJ commented on docs/tex/secciones/05_implementacion.tex
> +\textbf{Elección final:} \href{https://python-poetry.org/}{\textit{Poetry}}
Realmente hay otro, hash, que usa también pyproject.toml Lo principal no es decir lo que se ha elegido, sino que se siguen las buenas prácticas actuales. No se puede "decidir" sore el estándar, porque es estándar.

2022-09-28 10:40 UTC, JJ commented on docs/tex/secciones/05_implementacion.tex
> +\subsubsection{Herramientas ajenas a la programación.}
Supongo que quieres decir ajenas al código. Lo digo porque no has mencionado ni GitHub ni la herramienta de CI/CD que has usado, y si correspondería aquí o no. Quizás incluso deberías poner una sección de "infraestructura" y ponerla antes de la anterior, metiendo los editores, si acaso.

2022-09-28 19:17 UTC, Anglepi commented on docs/tex/secciones/05_implementacion.tex
> +Las historias de usuario se usan para definir funcionalidades que ciertos tipos de usuarios desean en determinadas situaciones. Cada una de estas historias de usuario representa un avance en la funci
Cierto, lo cambio

2022-09-28 19:22 UTC, Anglepi commented on docs/tex/secciones/05_implementacion.tex
> +Es un editor muy popular, que además recibe actualizaciones de manera frecuente con notables mejoras.
Te juro que he estado buscando porque cuando me dijiste que el Sublime no era una alternativa adecuada me quedé un poco loco, porque lo fui usando a lo largo de la carrera y en mi primer trabajo fue la norma, y no iba para nada mal.

Volví a investigar por internet y pregunté a amigos y compañeros de trabajo, porque me extrañó muchísimo, pero parece que no me equivocaba del todo...

2022-09-28 19:26 UTC, Anglepi commented on docs/tex/secciones/05_implementacion.tex
> +Finalmente se ha ido consensuando una buena práctica para estas gestiones, por lo que ésta ha de ser tenida en cuenta.
Está puesto en la justificación de la elección, un par de párrafos más abajo

2022-09-28 19:29 UTC, Anglepi commented on docs/tex/secciones/05_implementacion.tex
> +\textbf{Alternativa:} \href{https://pipenv-es.readthedocs.io/es/latest/}{\textit{Pipenv}}
Está abajo como indicaste, me he rayado casi una hora porque yo también lo veía mal, pero la rama tanto en el repo como en local están bien, pero ahora de repente si me voy a lo de _Files Changed_ se ve bien

2022-09-28 19:30 UTC, Anglepi commented on docs/tex/secciones/05_implementacion.tex
> +\subsubsection{Herramientas ajenas a la programación.}
Mmmmm puede molar, como poco el título de esta sección está mal, le echaré un ojo

2022-09-30 18:13 UTC, merged