[TS-3] API incorporation
Anglepi/My-Many-Reads pull request #52
Opened 2022-10-17 16:05 UTC by Anglepi

Changes included:

- Removed 3.7 and 3.8 versions of Python as supported versions.
- Tweaked and added some functions from Library and Book to make it easier to work from the API. Added tests when necessary.
- - Specifically one of them, removing empty list as default argument, due to Python doing dumb things
- Added API endpoints for books and libraries, using fastapi, and the related unit tests
- Added a couple targets to makefile: to start the server and an alias to generate docs.

uvicorn has been added as a dev dependency because probably is not a good idea to use it in production

Closes #45 
Closes #46 
Closes #47 
Closes #48 

Created #51 in the way, but this PR was growing a lot so I decided not to include anything else

# Code Review Actions

- [ ] Remove test data from `main.py` -> Won't do, not worth it at this point, will be replaced in the future
- [x] Rename `main.py` to `api.py`
- [x] Fix POST endpoints. Retrieve the location of the resource created and 201 status code. -> Created #54
- [x] Justify use of REST and how it is built -> Created #55
- [x] Remove API entities from the docs, it is not necessary
- [x] Emphasize the difference between synchronous and asynchronous API frameworks -> Created #55
- [x] Rename T-3.1 to be more specific
- [x] Rename first MVP

2022-10-19 13:14 UTC, JJ requested changes
El problema principal no está en el PR, sino en el desarrollo. Estás desarrollando el API antes de la lógica de negocio, lo que no acaba de encajar demasiado bien. La lógica de negocio debe ser un PMV anterior al API, porque es lo que añade más valor al producto.

2022-10-19 13:14 UTC, JJ commented on .github/workflows/spellcheck.yml
> +      - "**.md"
I think you need to use '**/*.md' , but really don't, because *.md is more than enough.

2022-10-19 13:14 UTC, JJ commented on docs/tex/secciones/05_implementacion.tex
> +\subsection{PMV-1. Estructura de datos básica y base de la lógica de negocio}
Una estructura de datos no es un PMV. Lo será si está en un fichero que cumpla una serie de características. Convendría que lo cambiaras, por si acaso.

2022-10-19 13:14 UTC, JJ commented on docs/tex/secciones/05_implementacion.tex
> +\subsection{PMV-2. Implementación de la API y sistema de recomendaciones}
Y esto deberías separarlo: una cosa es la API, otra la lógica de negocio. Hasta que no tengas la lógica de negocio no tienes el API, y si los metes en la misma, puedes acabar con un diseño muy acoplado.

2022-10-19 13:14 UTC, JJ commented on docs/tex/secciones/05_implementacion.tex
> +        \item \href{https://github.com/Anglepi/My-Many-Reads/issues/46}{\textbf{T-3.1}} Estructurar los cimientos de la API.
Esto es demasiado abstracto.

2022-10-19 13:14 UTC, JJ commented on docs/tex/secciones/05_implementacion.tex
> +        \item \href{https://github.com/Anglepi/My-Many-Reads/issues/48}{\textbf{T-3.2}} \textit{Endpoints} para las bibliotecas.
Deberías estructurarlo no sobre los URIs, sino sobre la funcionalidad a la que accedan.

2022-10-19 13:14 UTC, JJ commented on docs/tex/secciones/05_implementacion.tex
> +En Python existen muchas alternativas, y muy buenas, para construir una API. Todas parecen competir entre ellas en cuanto a velocidad, pues se publicitan mencionándola continuamente, pero en este cas
Deberías comentar la división que hay entre síncronos y asíncronos, que es la más importante.

2022-10-19 13:14 UTC, JJ commented on docs/tex/secciones/05_implementacion.tex
> +\begin{itemize}
Estás metiendo en el mismo saco un microframework y un framework MVC. Por favor, aclara también los ejes de distinción porque si no es un cajón de sastre.

2022-10-19 13:14 UTC, JJ commented on docs/tex/secciones/05_implementacion.tex
> +    \item \href{https://quart.palletsprojects.com/en/latest/}{\textit{Quart}} es, literalmente, una reimplementación de \textit{Flask} que permite asincronía.
Que es por lo que deberías incluir esa distinción desde el principio. Y poner algunos más que tengan esas características.

2022-10-19 13:14 UTC, JJ commented on docs/tex/secciones/05_implementacion.tex
> +\subsubsection{Entidades.}
En vez de las entidades (cuya enumeración no tiene mayor interés) di qué proceso has seguido para seleccionarlas.

2022-10-19 13:14 UTC, JJ commented on docs/tex/secciones/05_implementacion.tex
> +\end{itemize}
No pongas esto. ¿Qué sentido tiene?

2022-10-19 13:14 UTC, JJ commented on docs/tex/secciones/05_implementacion.tex
> +\subsubsection{\textit{Endpoints.}}
Supongo que lo irás a desarrollar, pero te digo lo mismo que arriba. Di el proceso de desarrollo del API y por qué has optado por un REST.

2022-10-19 13:14 UTC, JJ commented on mmr-backend/library.py
> +    def get_name(self):
¿hay algo en alguna HU que te pida estos datos? ¿O pones los getters a voleo?

2022-10-19 13:14 UTC, JJ commented on mmr-backend/book.py
>      edition: str
¿En algún lugar has justificado el layout del repositorio?

2022-10-19 13:14 UTC, JJ commented on mmr-backend/book.py
>      edition: str
me refiero, por qué `mmr-backend` y no `mmr/backend`, por ejemplo. O simplemente `mmr` si esto es todo lo que se va a hacer en Python

2022-10-19 13:14 UTC, JJ commented on mmr-backend/main.py
> +from ctypes.util import find_library
No entiendo ni este main ni la necesidad del mismo.

2022-10-19 13:14 UTC, JJ commented on mmr-backend/main.py
> +sample_data_path = "test/sample-data/books.json"
Si es un test, usa tests, que para eso están.

2022-10-19 13:14 UTC, JJ commented on mmr-backend/main.py
> +async def add_library_entry(user: str, library: str, isbn: str):
Tienes que seguir las buenas prácticas de devolver un URI único para lo que has añadido. Y en ese sentido, el URI representa al objeto, así que igual deberías llamarlo "book" y no "libraries".

2022-10-19 13:14 UTC, JJ commented on mmr-backend/main.py
> +@mmr.get("/books")
Deberías añadir algún middleware que hiciera comprobaciones.

2022-10-19 13:14 UTC, JJ commented on mmr-backend/main.py
> +@mmr.get("/books/{isbn}")
Ah, que este es el API. No lo llames main, sino API.

2022-10-19 13:14 UTC, JJ commented on mmr-backend/test/test_library.py
> +    library = Library(owner, name, [])
Tampoco entiendo muy bien el caso de uso aquí. ¿Hay alguno de alguien que ya tenga una biblioteca en no sé qué formato y vaya a importarla?

2022-10-19 13:14 UTC, JJ commented on mmr-backend/test/test_library.py
>      entry = get_sample_entries()[0]
No estás testeando lógica de negocio...

2022-10-22 07:39 UTC, Anglepi commented on mmr-backend/test/test_library.py
> +    library = Library(owner, name, [])
Así a voz de pronto no, pero no me pareció inconveniente dejar la posibilidad abierta por si acaso, quizás para una opción de clonar librerías o para importar.

Este cambio en concreto se debe a que descubrí que si en Python usas arrays como argumentos por defecto para funciones, no se genera un nuevo array con cada llamada sino que siempre usa el mismo provocando una especie de array singleton.

2022-10-22 07:42 UTC, Anglepi commented on mmr-backend/test/test_library.py
>      entry = get_sample_entries()[0]
Me gusta mantener el coverage a 100% para que al momento de desarrollar nuevas funcionalidades se me escapen menos cosas en los tests. Es cierto que hay algunos tests con menos sentido, pero es por esta razón

2022-10-22 07:48 UTC, Anglepi commented on mmr-backend/main.py
> +sample_data_path = "test/sample-data/books.json"
Me faltó poner un "manual" ahí, esto lo añadí al principio para cacharrear con el framework y ver que tal, pero sí, ya no hace nada de falta

2022-10-22 07:53 UTC, Anglepi commented on mmr-backend/library.py
> +    def get_name(self):
Facilitan mucho algunas tareas de la API, no está de más tenerlos creo yo

2022-10-22 07:54 UTC, JJ commented on mmr-backend/library.py
> +    def get_name(self):
No si no aportan valor.

2022-10-22 07:55 UTC, Anglepi commented on mmr-backend/book.py
>      edition: str
Pueees no realmente, no he hablado de esto en ninguna parte, es algo que sabía que iba a revisar en cuanto que añadiese quizás el frontend o cualquier otro componente

2022-10-22 07:58 UTC, Anglepi commented on docs/tex/secciones/05_implementacion.tex
> +\subsubsection{\textit{Endpoints.}}
Pues sí, mi idea era explicar todo esto en algún momento, pero ahora mismo es un buen momento, supongo que no lo puse por no agrandar más el PR

2022-10-22 07:59 UTC, Anglepi commented on docs/tex/secciones/05_implementacion.tex
> +\end{itemize}
Pues no sé la verdad, me puse a añadir los endpoints a la doc y por algún motivo pensé que esto también haría falta. Lo voy a quitar

2022-10-22 08:29 UTC, Anglepi commented on docs/tex/secciones/05_implementacion.tex
> +\begin{itemize}
Estoy buscando que opciones tengo para resolver el problema de construir una API, sin tener en cuenta cómo se categorizan esas opciones. Es cierto que Django y los demás son muy diferentes, pero aquí no estoy buscando "microframeworks para construir una API" si no "Posibles opciones para construir una API, y si de paso sirven para otras cosas pues también tenerlo en cuenta".

Yo creo que esta sección está bien, y añadir más opciones como indicas abajo tampoco lo veo absolutamente necesario. El rato que estuve mirando me parecieron todas iguales...

2022-10-22 08:30 UTC, Anglepi commented on docs/tex/secciones/05_implementacion.tex
> +En Python existen muchas alternativas, y muy buenas, para construir una API. Todas parecen competir entre ellas en cuanto a velocidad, pues se publicitan mencionándola continuamente, pero en este cas
Yes, anotado

2022-10-22 08:32 UTC, Anglepi commented on docs/tex/secciones/05_implementacion.tex
> +        \item \href{https://github.com/Anglepi/My-Many-Reads/issues/46}{\textbf{T-3.1}} Estructurar los cimientos de la API.
Especificaré

2022-10-22 08:32 UTC, Anglepi commented on docs/tex/secciones/05_implementacion.tex
> +        \item \href{https://github.com/Anglepi/My-Many-Reads/issues/48}{\textbf{T-3.2}} \textit{Endpoints} para las bibliotecas.
Ya se ha hecho así, no veo como podría cambiarlo, pero lo tendré en cuenta para el futuro

2022-10-22 08:38 UTC, JJ commented on docs/tex/secciones/05_implementacion.tex
> +\begin{itemize}
> Estoy buscando que opciones tengo para resolver el problema de construir una API, sin tener en cuenta cómo se categorizan esas opciones. Es cierto que Django y los demás son muy diferentes, pero aquí no estoy buscando "microframeworks para construir una API" si no "Posibles opciones para construir una API, y si de paso sirven para otras cosas pues también tenerlo en cuenta".
> 

Si no lo tienes en cuenta no lo pongas. O aclara claramente qué es lo que estás buscando. Meter en el mismo saco cosas muy diferentes y no meter cosas que sí son parecidas (como HAPI) no aporta nada.

> Yo creo que esta sección está bien, y añadir más opciones como indicas abajo tampoco lo veo absolutamente necesario. El rato que estuve mirando me parecieron todas iguales...

2022-10-22 08:40 UTC, JJ commented on docs/tex/secciones/05_implementacion.tex
> +        \item \href{https://github.com/Anglepi/My-Many-Reads/issues/48}{\textbf{T-3.2}} \textit{Endpoints} para las bibliotecas.
Lo que tienes que hacer, una vez más, es justificar las decisiones. Si has seguido buenas prácticas en el diseño de una API REST, menciona qué documento has seguido. No se trata de que cuentes qué has hecho, sino de que muestres qué metodología has seguido para tomar las decisiones que han configurado el proyecto.

2022-10-22 08:42 UTC, JJ commented on docs/tex/secciones/05_implementacion.tex
> +\end{itemize}
La memoria es para justificar las decisiones tomadas y explicar las diferentes metodologías seguidas, mostrando la madurez de la persona que lo ha hecho. No es "lo que hice el último verano" ni "mira qué bonico mi niño lo que hace". Tienes que aportar valor a la historia de usuario del tribunal.

2022-10-22 08:43 UTC, JJ commented on mmr-backend/book.py
>      edition: str
Es que eso es la memoria. Justificar las decisiones.

2022-10-22 08:44 UTC, JJ commented on mmr-backend/test/test_library.py
> +    library = Library(owner, name, [])
Si no hay caso de uso, no hay historia de usuario, si no hay historia de usuario, el código no aporta valor. Si eso es lo que quieres hacer, abre un ticket que explique esa característica como "technical story" que la has llamado, ¿no?

2022-10-22 08:45 UTC, JJ commented on mmr-backend/test/test_library.py
>      entry = get_sample_entries()[0]
Asignar valores a los atributos y recuperarlos no es código, por lo que no hacerlo no quita coverage. En todo caso, ¿dónde está la technical story del coverage? ¿Dónde está el informe que dice que con eso se aumente la cobertura?

2022-10-22 08:51 UTC, Anglepi commented on docs/tex/secciones/05_implementacion.tex
> +\subsection{PMV-2. Implementación de la API y sistema de recomendaciones}
Quise meter la API aquí, pronto, por estos motivos:

- Como da mucho valor al TFM, en caso de que lo entregara pronto y con falta de funcionalidades
- Si introducía más tarde, con más entidades y funcionalidades disponibles, me esperarían unos días de solo hacer endpoints muuuy monótonos, y quien sabe si al meter los endpoints más tarde descubría problemas que requirieran grandes refactorizaciones.
- Puedo separar este PMV en dos, por una parte la API (incluida en este PR) y por otra el sistema de recomendaciones si lo prefieres, estoy a tiempo. No lo hice así porque a mi parecer queda un PMV muy chico (esta es la única razón)

El PMV no es una implementación de API y recomendaciones en conjunto, es API y una vez esté, recomendaciones.

Dime si prefieres que lo separe o que lo renombre para que quede claro, independientemente yo creo que a nivel de desarrollo lo iba a hacer igual

2022-10-22 08:52 UTC, Anglepi commented on docs/tex/secciones/05_implementacion.tex
> +\subsection{PMV-1. Estructura de datos básica y base de la lógica de negocio}
Vale, lo cambio

2022-10-22 09:12 UTC, JJ commented on docs/tex/secciones/05_implementacion.tex
> +\subsection{PMV-2. Implementación de la API y sistema de recomendaciones}
Lo que aporta valor es que los PMVs sigan una secuencia lógica y que sean diferentes capas de abstracción. Si lo introduces ahora es prácticamente imposible refactorizar y, lo que es más importante, no muestra una metodología limpia. Lo dicho ya: el TFM no se trata de mostrar un producto. Se trata de mostrar que se conocen y se saben unar las metodologías que sirven para desarrollar productos.

2022-10-29 10:07 UTC, merged