49 recommendations created by users
Anglepi/My-Many-Reads pull request #63
Opened 2022-11-14 13:27 UTC by Anglepi

With this pull request I'm creating the data structure and logic to allow users create recommendations between pairs of books:

- Defined a data structure for recommendations. Closes #57 
- Defined all the required functionality and logic for it. Closes #58
- Created the necessary endpoints to access the relevant functionality. Closes #59 

As usual, I also updated the docs with the required information and implemented unit tests for all the new code.

I also included a minor tweak in the spellchecker and did some refactor in variable names.

2022-11-14 13:54 UTC, JJ requested changes
El principal es el diseño de las rutas, y el secundario es el *naming nit*. A partir de ahí, lo que mejor veas.
Ah, terciario que tienes que describir bien lo que estás haciendo, no enlazar el código. Quizás ese el principal, teniendo en cuenta cuál es el producto.

2022-11-14 13:54 UTC, JJ commented on docs/tex/secciones/05_implementacion.tex
> +Este sistema es uno de los puntos más importantes de la plataforma, pues es el que más atractivo aporta con respecto a los usuarios. Se compone, básicamente, de dos subsistemas: recomendaciones autom
¿Plataforma o proyecto?

2022-11-14 13:54 UTC, JJ commented on docs/tex/secciones/05_implementacion.tex
> +\begin{lstlisting}
No creo que al tribunal le interese el código. Mira #7

2022-11-14 13:54 UTC, JJ commented on docs/tex/secciones/05_implementacion.tex
> +Mediante algo de lógica se controla fácilmente la creación de recomendaciones, adición de comentarios a recomendaciones existentes y votaciones, los cuales se pueden ver fácilmente en \href{https://g
Tampoco funcionan muy bien estos enlaces. Yo resumiría los retos que se han superado y como se ha hecho.

2022-11-14 13:54 UTC, JJ commented on mmr-backend/api.py
> +    (mock_book_list[0].ISBN, mock_book_list[1].ISBN), UserRecommendation.UserComment("Recommender", "first book is similar to second book")),
Esto lo veo muy ad hoc. Pero bueno...

2022-11-14 13:54 UTC, JJ commented on mmr-backend/api.py
> +        lambda lib: lib.get_owner() == user, mock_libraries)
No entiendo bien. ¿usas mocks en el API? ¿No estarás queriendo decir una serialización de las mismas?

2022-11-14 13:54 UTC, JJ commented on mmr-backend/api.py
> +    return list(map(lambda book: Book.to_dict(book), mock_book_list))
No deberías usar la palabra "mock" si esto no es un test.

2022-11-14 13:54 UTC, JJ commented on mmr-backend/api.py
> +@mmr.get("/userRecommendations/{book}")
Sería más adecuado que fuera /recommendations/user
las rutas deben expresar la jerarquía de los objetos que estás transfiriendo.

2022-11-14 17:30 UTC, Anglepi commented on mmr-backend/api.py
> +    (mock_book_list[0].ISBN, mock_book_list[1].ISBN), UserRecommendation.UserComment("Recommender", "first book is similar to second book")),
Todo esto va a dejar de existir al comienzo del próximo hito cuando implemente algo de base de datos

2022-11-14 17:35 UTC, Anglepi commented on mmr-backend/api.py
> +@mmr.get("/userRecommendations/{book}")
Mmmmmm me da que pensar, se me ocurre lo siguiente: 

- /recommendations/{book} para las recomendaciones en base a un libro (son las creadas por usuarios)
- /recommendations/libraries/{user}/{library} para las recomendaciones autogeneradas en base a bibliotecas

2022-11-14 17:39 UTC, Anglepi commented on docs/tex/secciones/05_implementacion.tex
> +\begin{lstlisting}
Lo suponía, por eso puse un trozo pequeño y simplificado. Al ser tan chiquitito y simplón creo que ayuda un poco a entender esta parte, y de paso les recuerda que es un proyecto de informática.

Y si me dicen que no les gusta que ponga código, ya les debatiré esa opinión en la defensa, pero tomo nota, no recordaba que no se hacía mención a estas cosas en los criterios de evaluación

2022-11-14 17:40 UTC, Anglepi commented on docs/tex/secciones/05_implementacion.tex
> +Este sistema es uno de los puntos más importantes de la plataforma, pues es el que más atractivo aporta con respecto a los usuarios. Se compone, básicamente, de dos subsistemas: recomendaciones autom
Proyecto, mala mía

2022-11-14 17:43 UTC, JJ commented on mmr-backend/api.py
> +    (mock_book_list[0].ISBN, mock_book_list[1].ISBN), UserRecommendation.UserComment("Recommender", "first book is similar to second book")),
Lo que tendrías que hacer entonces es implementar inversión de dependencias. Es lo que evita este tipo de cosas.

2022-11-14 17:44 UTC, JJ commented on docs/tex/secciones/05_implementacion.tex
> +\begin{lstlisting}
No les debes debatir *nada* al tribunal. De hecho, no debes introducir nada debatible ni discutible en la memoria.
Se trata simplemente de que lo entienda cualquier persona del tribunal. Recuerda que puede haber personas de diferentes tribunales y con diferentes experiencias en programación (incluyendo ninguna)

2022-11-14 18:57 UTC, Anglepi commented on mmr-backend/api.py
> +    (mock_book_list[0].ISBN, mock_book_list[1].ISBN), UserRecommendation.UserComment("Recommender", "first book is similar to second book")),
Si, seguramente había soluciones buenas pensadas para este tipo de situaciones, pero sabía que iba a ser algo temporal.

Lo próximo a implementar será las recomendaciones autogeneradas en base a librerías, seguramente tenga que meter más ejemplos de libros pero una vez haga eso, el próximo paso será borrar todo esto para implementar una BD propiamente dicha

2022-11-14 18:58 UTC, Anglepi commented on docs/tex/secciones/05_implementacion.tex
> +Mediante algo de lógica se controla fácilmente la creación de recomendaciones, adición de comentarios a recomendaciones existentes y votaciones, los cuales se pueden ver fácilmente en \href{https://g
Entiendo lo que dices y tienes razón, a ver que se me ocurre para ponerlo mejor...

2022-11-15 15:22 UTC, Anglepi commented
Ya debería estar todo más guay

2022-11-15 16:22 UTC, JJ approved these changes
Has cambiado una parte pequeña de las cosas. Entiendo que tendrás tus razones para no hacer el resto, incluyendo el tiempo, así que no voy a poner más objeciones.

2022-11-15 16:36 UTC, merged

2023-04-17 07:18 UTC, JJ commented on docs/tex/secciones/05_implementacion.tex
> +\subsubsection{Recomendaciones de los usuarios}
Las recomendaciones de los usuarios en GoodReads son implícitas, embebidas, con un enlace estándar, en la reseña. Pueden aparecer o no, y generalmente yo no las pongo, pero en todo caso forman parte de una historia de usuario concreta: una persona quiere tener un registro de los libros que ha leído. Nadie *quiere* escribir recomendaciones de libros, y menos basadas en un sólo libro.

2023-04-17 07:19 UTC, JJ commented on docs/tex/secciones/05_implementacion.tex
> +Para cada pareja de libros, los usuarios podrán escribir un comentario para justificar la recomendación entre ambos libros. Otros usuarios podrán votar dichos comentarios con el fin de apoyar esa rec
Para "cada" pareja de libros suena todavía peor... De veras, no lo veo esto, ni veo que resuelva ningún problema. ¿Qué falta hace complementar las recomendaciones automáticas con estas manuales? ¿De qué forma añade valor al cliente?

2023-04-17 07:26 UTC, JJ reviewed
Estoy viendo que sólo tienes implementadas las recomendaciones de los usuarios, que además se pueden votar...
Mi recomendación, en este caso, es que simplemente elimines todo este código. Ni sirve a ninguna historia de usuario, ni realmente parece algo que un usuario quiera hacer, por mucho que sea ratón de biblioteca.
Tendrías que considerar también no mezclar niveles de abstracción en un mismo PR. El nivel de estructura de datos y lógica de negocio deberían haberse hecho en una etapa muy anterior a la implementación del API.

2023-04-17 07:26 UTC, JJ commented on docs/tex/secciones/05_implementacion.tex
> +Cada recomendación, por tanto, queda compuesta de una pareja de libros identificados por su \textit{ISBN}. Con el fin de encontrar recomendaciones concretas con mayor facilidad, esta pareja se ordena
¿Se ordena? ¿Cómo? Incluso aunque esto sirviera para #49 , ¿cómo priorizas una recomendación frente a otra?

2023-04-17 07:26 UTC, JJ commented on mmr-backend/api.py
> +    (mock_book_list[0].ISBN, mock_book_list[2].ISBN), UserRecommendation.UserComment("Recommender", "first book is similar to third book"))]
¿Para qué sirve el comentario en la lógica de negocio?

2023-04-17 07:26 UTC, JJ commented on mmr-backend/api.py
> +async def vote_user_recommendation(book1: str, book2: str, user: str, response: Response) -> Optional[dict]:
Totalmente perdido aquí. ¿Quién va a votar recomendaciones de usuarios? ¿A qué historia de usuario ayuda?

2023-04-17 07:26 UTC, JJ commented on mmr-backend/api.py
> +    if book1 == book2:
¿Y si son diferentes ediciones?