[TE-6] data management layer
Anglepi/My-Many-Reads pull request #83
Opened 2023-01-21 12:21 UTC by Anglepi

Created a data manager with the functionality that was done in the API and some fake data to work with while a real DB is implemented.

Closes #76 with all its tasks:

Closes #72 Closes #77 Closes #78 Closes #79 Closes #80

Since I consider that there is noticeable work missing for this data manager, I created #81 and #82

2023-01-21 12:26 UTC, JJ reviewed
Despite having worked on a number of issues, I see very little change in the documentation. I would expect the documentation to mirror the amount of work done in the code, and the challenges faced, and how they've been solved.

2023-01-21 12:32 UTC, Anglepi commented
> Despite having worked on a number of issues, I see very little change in the documentation. I would expect the documentation to mirror the amount of work done in the code, and the challenges faced, and how they've been solved.

Yes, since I found this still needs work (#82) I decided to not do any docs at the moment to avoid the risk of changing it all afterwards because of some possible breaking change, that's why I added #81.

I'm planning on doing a new PR with #81 and #82 alone after this one, depends on how I plan to solve #82

2023-01-23 08:15 UTC, JJ requested changes
Deberías aprovechar que hay tiempo para crear un gestor de datos abstracto (el dateador del que hablamos en CC) con una implementación concreta desde un fichero que se pueda usar en esta fase.
Y sigo insistiendo que no se usen datos concretos en el código, sólo en tests.

2023-01-23 08:15 UTC, JJ commented on docs/tex/secciones/05_implementacion.tex
> +La primera implementación de la API se introdujo en el segundo PMV (ver \nameref{pmv2}). En este momento, al ser una fase temprana del proyecto, se carecía de una base de datos, por lo que para poner
Y si lo incumple, ¿por qué no lo pones en el código de test, en vez de aquí mismo?
No tiene mucho que ver con ese principio, sin embargo; al menos que yo lo vea.

2023-01-23 08:15 UTC, JJ commented on docs/tex/secciones/05_implementacion.tex
> +En esta primera versión de la API, cada \textit{endpoint} consultaba los datos almacenados en una variable global, realizaba las operaciones necesarias sobre estos y devolvía la respuesta. Siguiendo
Deberías especificar que eso es simplemente parte del principio que dice que es necesario escribir código hasta que pase el test. No creo que haya mucha gente que sepa programación a ese nivel en el tribunal, pero si la hay te va a decir que código erróneo es código erróneo en la fase que sea.

2023-01-23 08:15 UTC, JJ commented on docs/tex/secciones/05_implementacion.tex
> +Con respecto al primer problema, se trata de algo que no habría ocurrido si se hubiese desarrollado la base de datos en primer lugar, seguida de la clase gestora de datos y finalmente por la API. Por
... y el desarrollo desacoplado en diferentes capas de abstracción que esto conlleva.

2023-01-23 08:15 UTC, JJ commented on mmr-backend/api.py
>  sample_data_path = "test/sample-data/books.json"
"For testing" code debería ir al directorio de test. No creo que haya ninguna razón funcional para que esto siga aquí, ahora que estás refactorizando.

2023-01-23 08:15 UTC, JJ commented on mmr-backend/api.py
> +data_manager: DataManager = DataManager(data_path)
Creo recordar que ibas a hacer inyección de dependencias. Si es así, esto debería ser un URI, que será manejado de forma diferente dependiendo del URI en si; o simplemente crear una clase base abstracta instanciada a DataManager concretos que usen diferentes fuentes de datos.
En todo caso, las variables globales siguen siendo un problema.

2023-01-23 08:15 UTC, JJ commented on mmr-backend/data_manager.py
> +        if self.connection:
No tiene mucho sentido mantener una conexión a un fichero abierta todo el tiempo. Deberías basar esto en una clase base abstracta, y usar inyección de dependencias (en este caso, al API)
Si no, vas  a tener que refactorizar esta clase cuando tengas que usar una base de datos o cualquier otra fuente de datos. Recuerda Open/Close

2023-01-23 16:47 UTC, Anglepi commented on mmr-backend/api.py
> +data_manager: DataManager = DataManager(data_path)
Con #82, que tengo pensado arreglar con un middleware, este problema desaparece.

2023-01-23 17:23 UTC, Anglepi commented on docs/tex/secciones/05_implementacion.tex
> +La primera implementación de la API se introdujo en el segundo PMV (ver \nameref{pmv2}). En este momento, al ser una fase temprana del proyecto, se carecía de una base de datos, por lo que para poner
Con respecto al principio de responsabilidad única en la API, ésta solo tiene que encargarse de las peticiones escuchándolas, enviando su información a otros componentes para que la procesen y devolver una respuesta.

Si la API está haciendo algún tipo de tratamiento de datos directamente, ya está haciendo más que escuchar y responder

2023-01-23 17:27 UTC, JJ commented on docs/tex/secciones/05_implementacion.tex
> +La primera implementación de la API se introdujo en el segundo PMV (ver \nameref{pmv2}). En este momento, al ser una fase temprana del proyecto, se carecía de una base de datos, por lo que para poner
... por eso hay que ponerlo en el test, y no aquí.

2023-01-28 10:05 UTC, merged